name: Package Nexus
on: [push, workflow_dispatch]
jobs:
 package:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v4
   - run: zip -r Nexus-Builder-Mobile.zip . -x '.git/*' -x '.nexus/*' -x 'workspace/*'
   - uses: actions/upload-artifact@v4
     with:
      name: Nexus-Builder-Mobile-ZIP
      path: Nexus-Builder-Mobile.zip
